### ISSUE TITLE
Should a task be considered correct if there are no successful terminations?

### ISSUE THREAD

**Issue by delcypher** [delcypher/klee-runner#7]
Due to e79d0df6416362906a5707c6900e45e2eac5be2c when a benchmark is executed with a single path and an assert fails it means there are no test cases that successfully terminate.

This causes the `get_klee_verification_result()` function to report `KleeResultUnknown` for other verification tasks (e.g. `no_overshift`)  with reason "Cannot verify because KLEE did not have any successful terminations".

This was originally put in as a sanity check that I wasn't expecting to hit, but now we hit it.

I think we should probably just report the benchmark as correct w.r.t to the other properties?

@ccadar @afd what do you think?

**Comment by delcypher** [comment]
@ccadar @afd : ping.

**Comment by afd** [comment]
Yes, I'd say so.

Ally

**Comment by ccadar** [comment]
I would say so too, but this further emphasises the need for coverage, as such behavior should be penalized there.
